import logging

import httpx

from src.ai.domain.provider import CompletionRequest, CompletionResult, LLMProvider
from src.shared.exceptions.exceptions import AppError

logger = logging.getLogger("talentflow.ai")


class MockLLMProvider(LLMProvider):
    def complete(self, request: CompletionRequest) -> CompletionResult:
        text = (
            f"[Generated by MockLLMProvider based on your input]\n\n{request.user_prompt}\n\n"
            "-- This is a deterministic placeholder response. Set AI_PROVIDER=openai_compatible "
            "and AI_API_KEY to use a real model. --"
        )
        return CompletionResult(text=text, provider="mock", model="mock-v1")


class OpenAICompatibleProvider(LLMProvider):
    """Works with OpenAI, Groq, OpenRouter, or any OpenAI-compatible
    /chat/completions endpoint — only base_url/model/key change."""

    def __init__(self, *, api_key: str, base_url: str, model: str, timeout_seconds: float = 20.0):
        self.api_key = api_key
        self.base_url = base_url.rstrip("/")
        self.model = model
        self.timeout_seconds = timeout_seconds

    def complete(self, request: CompletionRequest) -> CompletionResult:
        try:
            response = httpx.post(
                f"{self.base_url}/chat/completions",
                headers={"Authorization": f"Bearer {self.api_key}"},
                json={
                    "model": self.model,
                    "messages": [
                        {"role": "system", "content": request.system_prompt},
                        {"role": "user", "content": request.user_prompt},
                    ],
                    "max_tokens": request.max_tokens,
                    "temperature": request.temperature,
                },
                timeout=self.timeout_seconds,
            )
            response.raise_for_status()
            body = response.json()
            text = body["choices"][0]["message"]["content"]
            return CompletionResult(text=text, provider="openai_compatible", model=self.model)
        except (httpx.HTTPError, KeyError, IndexError) as exc:
            logger.error("ai_provider_call_failed", extra={"extra_fields": {"error": str(exc)}})
            raise AppError(
                "The AI provider is currently unavailable. Please try again shortly.",
                code="AI_PROVIDER_ERROR",
            ) from exc
